export const IMG_CDN_LINK = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"
export const SwiggyAPI_URL = "https://www.swiggy.com/dapi/restaurants/list/v5?&lat=18.516726&lng=73.856255";
export const ITEM_IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/";
export const MAIN_Restaurnat_API_URL = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=19.8761653&lng=75.3433139&restaurantId="

// menu items api card type key
export const MENU_ITEM_TYPE_KEY = "type.googleapis.com/swiggy.presentation.food.v2.ItemCategory";
export const RESTAURANT_TYPE_KEY = "type.googleapis.com/swiggy.presentation.food.v2.Restaurant";

// export const restaurantList = []
//  [
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "624011",
//           name: "Go Zero - Guilt Free Ice Creams",
//           uuid: "ae040250-ac22-4bd0-83d0-92b600de28b6",
//           city: "46",
//           area: "CIDCO",
//           totalRatingsString: "",
//           cloudinaryImageId: "jednzkl06xcsoffeeabk",
//           cuisines: ["Ice Cream", "Desserts"],
//           tags: [],
//           costForTwo: 15000,
//           costForTwoString: "₹150 FOR TWO",
//           deliveryTime: 16,
//           minDeliveryTime: 16,
//           maxDeliveryTime: 16,
//           slaString: "16 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "go-zero-guilt-free-ice-creams-jalna-road-cidco",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Jalna Road",
//           parentId: 343689,
//           unserviceable: false,
//           veg: true,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           aggregatedDiscountInfo: {
//             header: "50% off",
//             shortDescriptionList: [
//               {
//                 meta: "50% off | Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "50% off up to ₹100 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           aggregatedDiscountInfoV2: {
//             header: "50% OFF",
//             shortDescriptionList: [
//               {
//                 meta: "Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "50% off up to ₹100 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID:
//             "cid=7860468~p=1~eid=00000189-f9fb-d72e-3da1-b95800ba017c~srvts=1692116178734~78798",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "2.1 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=624011",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 16,
//             minDeliveryTime: 16,
//             maxDeliveryTime: 16,
//             lastMileTravel: 0,
//             lastMileDistance: 2.1,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: true,
//           avgRating: "4.3",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "449492",
//           name: "Aurangabad Bowl Company",
//           uuid: "a881cd60-6f65-47eb-96a4-5911fdae1dea",
//           city: "46",
//           area: "Nirala Bazar",
//           totalRatingsString: "",
//           cloudinaryImageId: "cff37de2e84b770ac54c412b150a3a11",
//           cuisines: ["Desserts", "Chinese", "North Indian", "Biryani"],
//           tags: [],
//           costForTwo: 30000,
//           costForTwoString: "₹300 FOR TWO",
//           deliveryTime: 17,
//           minDeliveryTime: 17,
//           maxDeliveryTime: 17,
//           slaString: "17 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "shubham-manik-ratnaparkhi-nirala-bazar-nirala-bazar",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Sahwas Nagar",
//           parentId: 313405,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           aggregatedDiscountInfo: {
//             header: "60% off",
//             shortDescriptionList: [
//               {
//                 meta: "60% off | Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "60% off up to ₹120 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           aggregatedDiscountInfoV2: {
//             header: "60% OFF",
//             shortDescriptionList: [
//               {
//                 meta: "Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "60% off up to ₹120 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID: "",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "1.5 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=449492",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 17,
//             minDeliveryTime: 17,
//             maxDeliveryTime: 17,
//             lastMileTravel: 0,
//             lastMileDistance: 1.5,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: false,
//           avgRating: "3.7",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "416867",
//           name: "Frozen Bottle - Milkshakes, Desserts And Ice Cream",
//           uuid: "2bd4f677-2fce-4778-abf2-05aa6efec0ce",
//           city: "46",
//           area: "Ulkanagari",
//           totalRatingsString: "",
//           cloudinaryImageId: "ok1d3jswkmlhlpdhjwvz",
//           cuisines: [
//             "Beverages",
//             "Desserts",
//             "Ice Cream",
//             "Waffle",
//             "Bakery",
//             "Healthy Food",
//           ],
//           tags: [],
//           costForTwo: 25000,
//           costForTwoString: "₹250 FOR TWO",
//           deliveryTime: 19,
//           minDeliveryTime: 19,
//           maxDeliveryTime: 19,
//           slaString: "19 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "frozen-bottle-garkheda-parisar-gadia-vihar",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Ulkanagri",
//           parentId: 5655,
//           unserviceable: false,
//           veg: true,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           aggregatedDiscountInfo: {
//             header: "25% off",
//             shortDescriptionList: [
//               {
//                 meta: "25% off | Use JUMBO",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "25% off up to ₹100 on orders above ₹499 | Use code JUMBO",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           aggregatedDiscountInfoV2: {
//             header: "25% OFF",
//             shortDescriptionList: [
//               {
//                 meta: "Use JUMBO",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "25% off up to ₹100 on orders above ₹499 | Use code JUMBO",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID:
//             "cid=7632822~p=2~eid=00000189-f9fb-d72e-3da1-b95900ba0234~srvts=1692116178734~78798",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "2 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=416867",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 19,
//             minDeliveryTime: 19,
//             maxDeliveryTime: 19,
//             lastMileTravel: 0,
//             lastMileDistance: 2,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: true,
//           avgRating: "4.5",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "74102",
//           name: "Hotel Rana Veg Non Veg Restaurant",
//           uuid: "b2c9e3f6-4c91-40dc-b412-0535ac42809a",
//           city: "46",
//           area: "CIDCO",
//           totalRatingsString: "",
//           cloudinaryImageId: "soyaqvcyiwrlenn07c7q",
//           cuisines: [
//             "North Indian",
//             "Maharashtrian",
//             "Punjabi",
//             "Chinese",
//             "Continental",
//             "Biryani",
//             "Tandoor",
//             "Beverages",
//             "Sweets",
//           ],
//           tags: [],
//           costForTwo: 25000,
//           costForTwoString: "₹250 FOR TWO",
//           deliveryTime: 18,
//           minDeliveryTime: 18,
//           maxDeliveryTime: 18,
//           slaString: "18 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "hotel-rana-veg-non-veg-restaurant-cannought-place-cidco",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Cannought Place",
//           parentId: 101414,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           aggregatedDiscountInfo: {
//             header: "40% off",
//             shortDescriptionList: [
//               {
//                 meta: "40% off | Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "40% off up to ₹80 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           aggregatedDiscountInfoV2: {
//             header: "40% OFF",
//             shortDescriptionList: [
//               {
//                 meta: "Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "40% off up to ₹80 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID: "",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "3 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=74102",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 18,
//             minDeliveryTime: 18,
//             maxDeliveryTime: 18,
//             lastMileTravel: 0,
//             lastMileDistance: 3,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: false,
//           avgRating: "3.9",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "661414",
//           name: "Sudhaj Kitchen ",
//           uuid: "11ef291d-645b-4dd9-9176-6317258afad7",
//           city: "46",
//           area: "Gadia Vihar",
//           totalRatingsString: "",
//           cloudinaryImageId: "a79403b3daea9a1ede0a7b1ec36bc943",
//           cuisines: ["Biryani", "Indian"],
//           tags: [],
//           costForTwo: 30000,
//           costForTwoString: "₹300 FOR TWO",
//           deliveryTime: 16,
//           minDeliveryTime: 16,
//           maxDeliveryTime: 16,
//           slaString: "16 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "sudhaj-kitchen-gadia-vihar-gadia-vihar",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Darga Road",
//           parentId: 396935,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID:
//             "cid=7868039~p=5~eid=00000189-f9fb-d72e-3da1-b95c00ba0570~srvts=1692116178734~78798",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "1.7 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=661414",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 16,
//             minDeliveryTime: 16,
//             maxDeliveryTime: 16,
//             lastMileTravel: 0,
//             lastMileDistance: 1.7,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: true,
//           avgRating: "4.8",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "94210",
//           name: "Gharghuti Kanduri Mutton Handi",
//           uuid: "5b75e461-8157-4650-9422-87b1244912ce",
//           city: "46",
//           area: "Garkheda",
//           totalRatingsString: "",
//           cloudinaryImageId: "tbv9hiinijwewvkfndu9",
//           cuisines: ["North Indian"],
//           tags: [],
//           costForTwo: 30000,
//           costForTwoString: "₹300 FOR TWO",
//           deliveryTime: 24,
//           minDeliveryTime: 24,
//           maxDeliveryTime: 24,
//           slaString: "24 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "gharghuti-kanduri-muton-hand-garkheda-gadia-vihar",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Vijay Nagar",
//           parentId: 87212,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           aggregatedDiscountInfo: {
//             header: "40% off",
//             shortDescriptionList: [
//               {
//                 meta: "40% off | Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "40% off up to ₹80 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           aggregatedDiscountInfoV2: {
//             header: "40% OFF",
//             shortDescriptionList: [
//               {
//                 meta: "Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "40% off up to ₹80 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID: "",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "0.3 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=94210",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 24,
//             minDeliveryTime: 24,
//             maxDeliveryTime: 24,
//             lastMileTravel: 0,
//             lastMileDistance: 0.3,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: false,
//           avgRating: "3.0",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "91055",
//           name: "Kareems Kabab & Biryani",
//           uuid: "9ac5b582-73f8-4c99-91d3-7840e8c39ee3",
//           city: "46",
//           area: "Chicalthana",
//           totalRatingsString: "",
//           cloudinaryImageId: "ebyzf47dlimmjkvncxnw",
//           cuisines: ["North Indian", "Biryani"],
//           tags: [],
//           costForTwo: 30000,
//           costForTwoString: "₹300 FOR TWO",
//           deliveryTime: 31,
//           minDeliveryTime: 31,
//           maxDeliveryTime: 31,
//           slaString: "31 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "kareems-kebabs-curries-biryanies-cidco-cidco",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Prozone Mall",
//           parentId: 115087,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID:
//             "cid=7868341~p=6~eid=00000189-f9fb-d72e-3da1-b95d00ba0677~srvts=1692116178734~78798",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "3 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=91055",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 31,
//             minDeliveryTime: 31,
//             maxDeliveryTime: 31,
//             lastMileTravel: 0,
//             lastMileDistance: 3,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: true,
//           avgRating: "3.8",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "586863",
//           name: "Golden Chopstick Chinese 2",
//           uuid: "d74c533d-d015-442d-903e-f2a9dd92d9d1",
//           city: "46",
//           area: "Gadia Vihar",
//           totalRatingsString: "",
//           cloudinaryImageId: "wylznu4vwbyqd2zjvb4p",
//           cuisines: ["Chinese"],
//           tags: [],
//           costForTwo: 20000,
//           costForTwoString: "₹200 FOR TWO",
//           deliveryTime: 18,
//           minDeliveryTime: 18,
//           maxDeliveryTime: 18,
//           slaString: "18 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "golden-chopstick-chinese-2-gadia-vihar-gadia-vihar",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Sukhad Sahwas Nagar",
//           parentId: 351167,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           aggregatedDiscountInfo: {
//             header: "60% off",
//             shortDescriptionList: [
//               {
//                 meta: "60% off | Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "60% off up to ₹120 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           aggregatedDiscountInfoV2: {
//             header: "60% OFF",
//             shortDescriptionList: [
//               {
//                 meta: "Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "60% off up to ₹120 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID: "",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "1.5 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=586863",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 18,
//             minDeliveryTime: 18,
//             maxDeliveryTime: 18,
//             lastMileTravel: 0,
//             lastMileDistance: 1.5,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: false,
//           avgRating: "3.3",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "466105",
//           name: "Sapna Momos",
//           uuid: "ae47bf9b-0e4e-4612-aa1a-0dbf8a419efe",
//           city: "46",
//           area: "CIDCO",
//           totalRatingsString: "",
//           cloudinaryImageId: "ktczd3kif6fdeki9rdu5",
//           cuisines: ["Chinese"],
//           tags: [],
//           costForTwo: 20000,
//           costForTwoString: "₹200 FOR TWO",
//           deliveryTime: 23,
//           minDeliveryTime: 23,
//           maxDeliveryTime: 23,
//           slaString: "23 MINS",
//           lastMileTravel: 0,
//           slugs: { restaurant: "sapna-momos-cidco-cidco", city: "Aurangabad" },
//           cityState: "46",
//           address: "",
//           locality: "Pisadevi Road",
//           parentId: 279982,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID:
//             "cid=7875826~p=7~eid=00000189-f9fb-d72e-3da1-b95e00ba0731~srvts=1692116178734~78798",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "3 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=466105",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 23,
//             minDeliveryTime: 23,
//             maxDeliveryTime: 23,
//             lastMileTravel: 0,
//             lastMileDistance: 3,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: true,
//           avgRating: "4.0",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "402140",
//           name: "Pooja Family Restaurant",
//           uuid: "2c91b0e7-01da-4f2a-bd78-d8fbb5e5ab15",
//           city: "46",
//           area: "Nyay Nagar",
//           totalRatingsString: "",
//           cloudinaryImageId: "cxx0ltahygw8pawrz9z8",
//           cuisines: [
//             "Indian",
//             "Chinese",
//             "Pastas",
//             "North Indian",
//             "Tandoor",
//             "Snacks",
//             "Biryani",
//           ],
//           tags: [],
//           costForTwo: 50000,
//           costForTwoString: "₹500 FOR TWO",
//           deliveryTime: 16,
//           minDeliveryTime: 16,
//           maxDeliveryTime: 16,
//           slaString: "16 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "pooja-family-restaurant-gadia-vihar-gadia-vihar",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Pundlik Nagar",
//           parentId: 252824,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID: "",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "0.4 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=402140",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 16,
//             minDeliveryTime: 16,
//             maxDeliveryTime: 16,
//             lastMileTravel: 0,
//             lastMileDistance: 0.4,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: false,
//           avgRating: "3.7",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "698085",
//           name: "HFC Cloud Kitchen Operated By ORIGIN FOODS",
//           uuid: "0b4ea2b0-164b-46c5-ae53-269933f864fe",
//           city: "46",
//           area: "Garkheda Parisar",
//           totalRatingsString: "",
//           cloudinaryImageId: "f34657e4f398eec0e714971b58f8be69",
//           cuisines: ["Indian", "Snacks"],
//           tags: [],
//           costForTwo: 40000,
//           costForTwoString: "₹400 FOR TWO",
//           deliveryTime: 21,
//           minDeliveryTime: 21,
//           maxDeliveryTime: 21,
//           slaString: "21 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "origin-foods-usmanpura-usmanpura",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Ashok Nagar",
//           parentId: 417404,
//           unserviceable: false,
//           veg: true,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           aggregatedDiscountInfo: {
//             header: "10% off",
//             shortDescriptionList: [
//               {
//                 meta: "10% off | Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "10% off up to ₹40 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           aggregatedDiscountInfoV2: {
//             header: "10% OFF",
//             shortDescriptionList: [
//               {
//                 meta: "Use TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             descriptionList: [
//               {
//                 meta: "10% off up to ₹40 | Use code TRYNEW",
//                 discountType: "Percentage",
//                 operationType: "RESTAURANT",
//               },
//             ],
//             subHeader: "",
//             headerType: 0,
//             superFreedel: "",
//           },
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID:
//             "cid=7668272~p=8~eid=00000189-f9fb-d72e-3da1-b95f00ba082d~srvts=1692116178734~78798",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "1.1 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=698085",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 21,
//             minDeliveryTime: 21,
//             maxDeliveryTime: 21,
//             lastMileTravel: 0,
//             lastMileDistance: 1.1,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: true,
//           avgRating: "--",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "393432",
//           name: "Sai Bhel",
//           uuid: "eb79184b-7938-4849-8ca7-493c9146d96c",
//           city: "46",
//           area: "Nyay Nagar",
//           totalRatingsString: "",
//           cloudinaryImageId: "xeqdhdvx30unzsdcszsx",
//           cuisines: ["Chinese", "Chaat"],
//           tags: [],
//           costForTwo: 10000,
//           costForTwoString: "₹100 FOR TWO",
//           deliveryTime: 21,
//           minDeliveryTime: 21,
//           maxDeliveryTime: 21,
//           slaString: "21 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "sai-bhel-usmanpura-usmanpura",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Manak Nagar",
//           parentId: 174929,
//           unserviceable: false,
//           veg: true,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID: "",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "0.4 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=393432",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 21,
//             minDeliveryTime: 21,
//             maxDeliveryTime: 21,
//             lastMileTravel: 0,
//             lastMileDistance: 0.4,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: false,
//           avgRating: "3.8",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "99251",
//           name: "Hotel Jalgaon Bharit Centre",
//           uuid: "63220554-fd2b-4065-9cb0-a5b8e164fe05",
//           city: "46",
//           area: "CIDCO",
//           totalRatingsString: "",
//           cloudinaryImageId: "ekqkvhozxlxxtezpy3vn",
//           cuisines: ["North Indian"],
//           tags: [],
//           costForTwo: 35000,
//           costForTwoString: "₹350 FOR TWO",
//           deliveryTime: 25,
//           minDeliveryTime: 25,
//           maxDeliveryTime: 25,
//           slaString: "25 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "hotel-jalgaon-bharit-centre-cidco-cidco",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Avishkar Chowk",
//           parentId: 99479,
//           unserviceable: false,
//           veg: true,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID:
//             "cid=7868021~p=9~eid=00000189-f9fb-d72e-3da1-b96000ba0911~srvts=1692116178734~78798",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "3 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=99251",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 25,
//             minDeliveryTime: 25,
//             maxDeliveryTime: 25,
//             lastMileTravel: 0,
//             lastMileDistance: 3,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: true,
//           avgRating: "4.1",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//     {
//       cardType: "restaurant",
//       layoutAlignmentType: "VERTICAL",
//       data: {
//         type: "restaurant",
//         data: {
//           type: "F",
//           id: "114113",
//           name: "Hotel Nitin Maratha",
//           uuid: "479ed976-0eca-4077-a21e-f01b664e4db6",
//           city: "46",
//           area: "Nyay Nagar",
//           totalRatingsString: "",
//           cloudinaryImageId: "yqn5yroxiixfjbvulhpt",
//           cuisines: ["Maharashtrian", "North Indian"],
//           tags: [],
//           costForTwo: 30000,
//           costForTwoString: "₹300 FOR TWO",
//           deliveryTime: 19,
//           minDeliveryTime: 19,
//           maxDeliveryTime: 19,
//           slaString: "19 MINS",
//           lastMileTravel: 0,
//           slugs: {
//             restaurant: "hotel-nitin-maratha-gadia-vihar-gadia-vihar",
//             city: "Aurangabad",
//           },
//           cityState: "46",
//           address: "",
//           locality: "Reliance Mall",
//           parentId: 100811,
//           unserviceable: false,
//           veg: false,
//           select: false,
//           favorite: false,
//           tradeCampaignHeaders: [],
//           chain: [],
//           feeDetails: {
//             fees: [
//               { name: "BASE_DISTANCE", fee: 1900, message: "" },
//               { name: "BASE_TIME", fee: 0, message: "" },
//               { name: "ANCILLARY_SURGE_FEE", fee: 0, message: "" },
//             ],
//             totalFees: 1900,
//             message: "",
//             title: "Delivery Charge",
//             amount: "1900",
//             icon: "",
//           },
//           availability: {
//             opened: true,
//             nextOpenMessage: "",
//             nextCloseMessage: "",
//           },
//           longDistanceEnabled: 0,
//           rainMode: "NONE",
//           thirdPartyAddress: false,
//           thirdPartyVendor: "",
//           adTrackingID: "",
//           badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
//           lastMileTravelString: "0.3 kms",
//           hasSurge: false,
//           cta: {
//             link: "swiggy://menu?restaurant_id=114113",
//             type: "DEEPLINK",
//             text: "RESTAURANT_MENU",
//           },
//           sla: {
//             restaurantId: "",
//             deliveryTime: 19,
//             minDeliveryTime: 19,
//             maxDeliveryTime: 19,
//             lastMileTravel: 0,
//             lastMileDistance: 0.3,
//             serviceability: "SERVICEABLE",
//             rainMode: "NONE",
//             preferentialService: false,
//             iconType: "EMPTY",
//           },
//           promoted: false,
//           avgRating: "3.8",
//           totalRatings: 0,
//           new: false,
//         },
//         subtype: "basic",
//       },
//       parentWidget: false,
//     },
//   ];

 