
// export { default as Header} from "./Header/Header"
export {default as Header} from "./Header/Header"
export {default as Body} from "./Body/Body"
export {default as RestaurantCard} from "./RestaurantCard/RestaurantCard"
export {default as Footer} from "./Footer/Footer"
export {default as About} from "./About/About"
export {default as Error} from "./Error/Error"
export {default as ShimmarUI} from "./ShimmarUI/ShimmarUI"
export {default as MainRestaurant} from "./MainRestaurant/MainRestaurant"